### ISSUE TITLE
Possible Inverse Behavior

### ISSUE THREAD

**Issue by nigeltiany** [gswly/mavp2p#1]
https://github.com/gswly/mavp2p/blob/f1528741c681060fc5999bec73f77651204e53c2/main.go#L94

https://github.com/gswly/mavp2p/blob/f1528741c681060fc5999bec73f77651204e53c2/main.go#L194

When the ```print-errors``` flag is set, the pointer will be true and the goroutine won't run and errors won't be printed.

**Comment by gswly** [comment]
Hello, thanks for the report, effectively the flag is not clear enough. This is the desired behavior:

* when mavp2p is launched with the default options, and errors are detected, their quantity is printed every 5 seconds, and that's what that goroutine does, i.e:
  > 20 errors in the last 5 seconds

* when mavp2p is launched with --print-errors, and errors are detected, every single error is printed individually:
  > ERR: wrong magic byte \x45
  > ERR: wrong magic byte \x48

* when mavp2p is launched with --quiet, and errors are detected, errors are not printed.

Please note that parse errors are quite common, since Mavlink is usually routed through radio signals, serial ports and UDP, and none of those has a validation mechanism.
Moreover, the stream is usually already started when we launch mavp2p, so we usually start reading in the middle of a frame, and we must discard every byte up to the magic byte (the byte that signals the start of a frame) of the next frame.

Suggestions are welcome.
